import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import AuthProvider from "./auth/Provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anklesaria Lab Reporting",
  description: "Generated by Anklesaria Hospitals",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter" >
      <body className={inter.className}>
        <AuthProvider>
        <Navbar />
        <main className="p-0 bg-sky-200">
        {children}  
        </main>
        </AuthProvider>
        </body>
    </html>
  );
}
