-- DropForeignKey
ALTER TABLE `report` DROP FOREIGN KEY `Report_IPDNo_fkey`;

-- AlterTable
ALTER TABLE `report` MODIFY `IPDNo` VARCHAR(191) NOT NULL;

-- AlterTable
ALTER TABLE `user` MODIFY `IPDNo` VARCHAR(191) NOT NULL;

-- AddForeignKey
ALTER TABLE `Report` ADD CONSTRAINT `Report_IPDNo_fkey` FOREIGN KEY (`IPDNo`) REFERENCES `User`(`IPDNo`) ON DELETE RESTRICT ON UPDATE CASCADE;
